services:
  - type: web
    name: pantameteo-staging
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: WU_API_KEY
        sync: false
      - key: TEMPEST_TOKEN
        sync: false
    plan: free
    healthCheckPath: /
